- hosts: localhost
  become: yes
  gather_facts: no


  tasks:

   - name: Create Ministerio de Sanidad Organization
     ansible.controller.organization:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "Ministerio Sanidad"
       state: absent

   - name: Create Ministerio de Sanidad Organization
     ansible.controller.organization:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "Ministerio de Sanidad"
       state: present

   - name: Create Github credentials
     ansible.controller.credential:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       name: "Github credential"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       state: present
       credential_type: Source Control
       inputs:
         username: "{{ myghusr }}"
         password: "{{ myghtke }}"

   - name: Create Machine Credentials for localhost
     ansible.controller.credential:
       name: Localhost credentials
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       state: present
       credential_type: Machine
       inputs:
         username: root
         password: "{{  myrootpss }}"

   - name: Add my simple demo inventory
     ansible.controller.inventory:
       name: "My simple demo inventory"
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       state: present

   - name: Add my simple demo project
     ansible.controller.project:
       name: "My simple demo project"
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       scm_type: git
       scm_url: https://github.com/pablo-preciado/minsan-demo.git
       credential: Github credential
       scm_update_on_launch: True
       scm_clean: yes
       scm_delete_on_update: yes
       scm_update_cache_timeout: 0
       default_environment: "Default execution environment"
       state: present

   - name: Add an inventory source
     ansible.controller.inventory_source:
       name: "Github inventory source"
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       inventory: "My simple demo inventory"
       organization: "Ministerio de Sanidad"
       source: scm
       source_path: inventory/hosts
       source_project: "My simple demo project"
       overwrite: True
       overwrite_vars: yes
       update_on_launch: True

   - name: Launch a my simple demo project update
     ansible.controller.project_update:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       project: "My simple demo project"

   - name: Create "Simple demo create file" job template
     ansible.controller.job_template:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "Simple demo create file"
       job_type: "run"
       organization: "Ministerio de Sanidad"
       inventory: "My simple demo inventory"
       project: "My simple demo project"
       playbook: "simple-demo-create-file.yml"
       credentials: "Localhost credentials"
       state: "present"

   - name: Create "Simple demo delete file" job template
     ansible.controller.job_template:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "Simple demo delete file"
       job_type: "run"
       organization: "Ministerio de Sanidad"
       inventory: "My simple demo inventory"
       project: "My simple demo project"
       playbook: "simple-demo-delete-file.yml"
       credentials: "Localhost credentials"
       state: "present"
