- hosts: localhost
  become: yes
  gather_facts: no


  tasks:

#The following tasks are aiming at configuring our MySQL database automation demo

   - name: Create Ministerio de Sanidad Organization
     ansible.controller.organization:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "Ministerio Sanidad"
       state: present

   - name: Create Github credentials
     ansible.controller.credential:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       name: Github credential
       validate_certs: no
       organization: "Ministerio de Sanidad"
       state: present
       credential_type: Source Control
       inputs:
         username: "{{ myghusr }}"
         password: "{{ myghtke }}"

   - name: Create Machine Credentials for localhost
     ansible.controller.credential:
       name: Localhost credentials
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       state: present
       credential_type: Machine
       inputs:
         username: root
         password: "{{  myrootpss }}"

   - name: Add my simple demo inventory
     ansible.controller.inventory:
       name: "My simple demo inventory"
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       description: "This is a simple inventory from a github repository"
       instance_groups: "remote_exec"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       state: present

   - name: Add MySQL demo project
     ansible.controller.project:
       name: "MySQL demo project"
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       description: "This project is for managing mysql databases."
       organization: "Ministerio de Sanidad"
       scm_type: git
       scm_url: https://github.com/pablo-preciado/mysql-test.git
       credential: Github credential
       scm_update_on_launch: True
       scm_clean: yes
       scm_delete_on_update: yes
       scm_update_cache_timeout: 0
       default_environment: "Default execution environment"
       state: present

   - name: Add an inventory source
     ansible.controller.inventory_source:
       name: "Github inventory source"
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       description: Source for inventory
       inventory: "My simple demo inventory"
       organization: "Ministerio de Sanidad"
       source: scm
       source_path: inventory/hosts
       source_project: "MySQL demo project"
       overwrite: True
       overwrite_vars: yes
       update_on_launch: True

   - name: Launch a MySQL demo project
     ansible.controller.project_update:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       organization: "Ministerio de Sanidad"
       project: "MySQL demo project"

   - name: Add MySQL EE to the controller instance > this one is on github
     ansible.controller.execution_environment:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "MySQL EE"
       image: ghcr.io/pablo-preciado/mysql-test/mysql-ee:20
       credential: ghcr.io credential

   - name: Create "Install MySQL" job template
     ansible.controller.job_template:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "Install MySQL"
       job_type: "run"
       organization: "Ministerio de Sanidad"
       inventory: "Inventory file from Github"
       project: "MySQL demo project"
       playbook: "install-n-start-mysql.yml"
       instance_groups: "remote_exec"
       verbosity: 3
       credentials: "MySQL host credentials"
       state: "present"

   - name: Create "Create DB" job template
     ansible.controller.job_template:
       controller_host: "{{ mydemocontr }}"
       controller_username: "{{ myusrcontr }}"
       controller_password: "{{ mypsscontr }}"
       validate_certs: no
       name: "Create DB bobdata"
       job_type: "run"
       organization: "Ministerio de Sanidad"
       inventory: "Inventory file from Github"
       project: "MySQL demo project"
       playbook: "db-creation-test.yml"
       execution_environment: "MySQL EE"
       instance_groups: "remote_exec"
       verbosity: 3
       credentials: "MySQL host credentials"
       state: "present"
