- hosts: localhost
  gather_facts: no
  become: true

  vars:    
    ansible_python_interpreter: auto

  tasks:

   - name: Install the latest version of httpd
     ansible.builtin.yum:
       name: nano
       state: latest


