- hosts: localhost
  gather_facts: no
  become: true
  
  vars:    
    ansible_python_interpreter: auto

  tasks:

   - name: Uninstall httpd
     ansible.builtin.dnf:
       name: nano
       state: absent