- hosts: localhost
  gather_facts: no
  become: true

  tasks:

   - name: Delete my-simple-demo-file.txt file in /tmp
     ansible.builtin.file:
       path: /tmp/my-simple-demo-file.txt
       state: absent

